version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install --global yarn
  pre_build:
    commands:
      - yarn install
      - eval "artifact_dir=\$CODEBUILD_SRC_DIR_deploy" && cd $artifact_dir && BUCKET=$(jq -r .Bucket outputs.json)
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/apps/cleaved-app
      - yarn prod:us
  post_build:
    commands:
      - aws s3 sync $CODEBUILD_SRC_DIR/apps/cleaved-app/build s3://$BUCKET --delete
